---
- hosts: localhost
  remote_user: root
  tasks:
    - stat:
          path: ~/.ssh/id_rsa.pub
      register: rsa_key

    - name: Generating RSA key
      shell: ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa
      when: rsa_key.stat.islnk is not defined
    - name: deplay SSH Key for all host using root \ "{{ ssh_password }}" 
      shell: sshpass -p {{ ssh_password }} ssh-copy-id -o StrictHostKeyChecking=no root@{{ item }}
      with_items: "{{ groups['nodes'] }}"

- hosts: nodes
  remote_user: root
  tasks:
      #TODO: Add hostname validataion
      #TODO" edit auto server

#    - name: Validate correctnce of hostname
#      hostname:
#        name: "{{ lookup('dig', '10.8.196.81/PTR')}}"
#      when: not ("{{ lookup('dig', '10.8.196.81/PTR') }}" == ansible_default_ipv4.address)

    - name: Update subscription auth server
      replace:
          path: /etc/rhsm/rhsm.conf
          regexp: 'hostname = (.*)'
          replace: 'hostanem = {{ auth_server}}'
          backup: yes

    - name: Register as user ("{{ subscription_username }}").
      redhat_subscription:
          state: present
          username: "{{ subscription_username }}"
          password: "{{ subscription_password }}"
          autosubscribe: true

    - name: Enable repositories
      shell: subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-ose-3.7-rpms" --enable="rhel-7-fast-datapath-rpms"
  
    - name: Updating yum to latest
      yum:
          name: '*'
          state: latest
    - name: Install OCP reqired packages\rpms
      yum:
          name: "{{ item }}"
          state: latest
      with_items:
          - atomic-openshift-excluder 
          - atomic-openshift-docker-excluder 
          - atomic-openshift-utils
          - wget
          - git
          - net-tools
          - bind-utils
          - iptables-services
          - bridge-utils
          - bash-completion
          - kexec-tools
          - sos
          - psacct
          - sshpass  

    - name: Post installations actions
      shell: atomic-openshift-excluder unexclude


